# Generated by Django 6.1.1 on 2026-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("CLIENT_ADMIN", "Client Admin"),
                    ("CLIENT_USER", "Client User"),
                    ("MAINTENANCE", "Maintenance"),
                ],
                default="CLIENT_USER",
                max_length=20,
            ),
        ),
    ]
