# Generated by Django 6.1.1 on 2026-10-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="card_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Card payment fee, % of the card amount",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="extra_person_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Per extra person, per night",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="included_guests",
            field=models.PositiveSmallIntegerField(
                default=2, help_text="Guests included in the room rate"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="pet_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Per pet, per stay",
                max_digits=10,
            ),
        ),
    ]
