# Generated by Django 6.1.1 on 2026-10-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_client_card_fee_percent_client_extra_person_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="late_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Late checkout fee",
                max_digits=10,
            ),
        ),
    ]
