# Generated by Django 6.1.1 on 2026-10-05 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_client_late_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="day_change_time",
            field=models.TimeField(
                default=datetime.time(11, 0),
                help_text="Business day changes automatically at this time",
            ),
        ),
    ]
