# Generated by Django 6.1.1 on 2026-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_client_day_change_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="early_checkin_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Early check-in fee",
                max_digits=10,
            ),
        ),
    ]
