# Generated by Django 6.1.1 on 2026-10-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_early_checkin_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="scan_folder",
            field=models.CharField(
                blank=True,
                help_text="Folder on this PC where the printer saves scans",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="scanner_address",
            field=models.CharField(
                blank=True,
                help_text="Printer IP for direct scan (eSCL / AirScan)",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="scanner_area",
            field=models.CharField(
                default="DL",
                help_text="DL = card size in the top-left corner, PAGE = full page",
                max_length=8,
            ),
        ),
    ]
