# Generated by Django 6.1.1 on 2026-10-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_scanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="session_key",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
