# Generated by Django 6.1.1 on 2026-10-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="adjustment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
