# Generated by Django 6.1.1 on 2026-10-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motel", "0003_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="monthly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="weekly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="stay",
            name="periods",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="stay",
            name="rate_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                ],
                default="DAILY",
                max_length=10,
            ),
        ),
    ]
