# Generated by Django 6.1.1 on 2026-10-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motel", "0004_roomtype_monthly_rate_roomtype_weekly_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="card_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="stay",
            name="extra_person_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="stay",
            name="extra_persons",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stay",
            name="pet_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="stay",
            name="pets",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
