# Generated by Django 6.1.1 on 2026-10-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motel", "0007_guest_dnr_marked_at_guest_dnr_marked_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="kind",
            field=models.CharField(
                choices=[("PAYMENT", "Payment"), ("REFUND", "Refund")],
                default="PAYMENT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="stay",
            name="early_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stay",
            name="late_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="stay",
            name="room_charge_override",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
