# Generated by Django 6.1.1 on 2026-10-05 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    # Existing payments: count them on the calendar day they were taken (same as before).
    from django.utils import timezone
    Payment = apps.get_model("motel", "Payment")
    for p in Payment.objects.filter(business_date__isnull=True).only("id", "paid_at"):
        Payment.objects.filter(pk=p.pk).update(business_date=timezone.localdate(p.paid_at))


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_client_day_change_time"),
        ("motel", "0008_payment_kind_stay_early_snapshot_stay_late_fee_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="business_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="DayClose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("closed_at", models.DateTimeField()),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_closes",
                        to="accounts.client",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="day_closes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("client", "date")},
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
