# Generated by Django 6.1.1 on 2026-10-05 14:26

from django.db import migrations, models


def split_existing(apps, schema_editor):
    # existing guests: first word = first name, last word = last name, the rest = middle name
    Guest = apps.get_model("motel", "Guest")
    for g in Guest.objects.all().only("id", "name"):
        words = (g.name or "").split()
        if not words:
            continue
        first, middle, last = (words[0], "", "") if len(words) == 1 else (words[0], " ".join(words[1:-1]), words[-1])
        Guest.objects.filter(pk=g.pk).update(first_name=first[:60], middle_name=middle[:60], last_name=last[:60])


class Migration(migrations.Migration):

    dependencies = [
        ("motel", "0009_payment_business_date_dayclose"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="first_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="guest",
            name="last_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="guest",
            name="middle_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="guest",
            name="name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(split_existing, migrations.RunPython.noop),
    ]
