# Generated by Django 6.1.1 on 2026-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motel", "0011_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="dl_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=40,
                verbose_name="Driving licence number",
            ),
        ),
    ]
