# Generated by Django 6.1.1 on 2026-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motel", "0012_guest_dl_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="early_checkin_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
