# Generated by Django 6.1.1 on 2026-10-06 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_scanner"),
        ("motel", "0016_custom_reports"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="hk_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="room",
            name="hk_status",
            field=models.CharField(
                choices=[
                    ("READY", "Ready"),
                    ("DIRTY", "Dirty"),
                    ("CLEANING", "Cleaning"),
                    ("OUT_OF_ORDER", "Out of order"),
                ],
                default="READY",
                max_length=14,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="hk_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="hk_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="kind",
            field=models.CharField(
                choices=[
                    ("DL_FRONT", "DL front"),
                    ("DL_BACK", "DL back"),
                    ("DAMAGE", "Room damage"),
                    ("ISSUE", "Room problem"),
                ],
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="RoomIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PLUMBING", "Plumbing"),
                            ("ELECTRICAL", "Electrical"),
                            ("AC_HEAT", "AC / Heat"),
                            ("TV_WIFI", "TV / WiFi"),
                            ("FURNITURE", "Furniture"),
                            ("PESTS", "Pests"),
                            ("CLEANLINESS", "Cleanliness"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=12,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=8,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In progress"),
                            ("FIXED", "Fixed"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("made_out_of_order", models.BooleanField(default=False)),
                ("fixed_at", models.DateTimeField(blank=True, null=True)),
                ("history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_issues",
                        to="accounts.client",
                    ),
                ),
                (
                    "fixed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="motel.room",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="photo",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="motel.roomissue",
            ),
        ),
        migrations.CreateModel(
            name="RoomStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("STATUS", "Status"),
                            ("SERVICE", "Service"),
                            ("OVERRIDE", "Rented while not ready"),
                        ],
                        max_length=10,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=14)),
                ("to_status", models.CharField(blank=True, max_length=14)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("business_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_logs",
                        to="accounts.client",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="motel.room",
                    ),
                ),
                (
                    "stay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="motel.stay",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
