# Generated by Django 6.1.1 on 2026-10-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motel", "0017_housekeeping_and_problems"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="extra_stay_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="stay",
            name="extra_stay_nights",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
