# Generated by Django 6.1.1 on 2026-10-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motel", "0018_stay_extra_stay"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="balance_carried",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
