# Generated by Django 6.1.1 on 2026-10-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motel", "0019_stay_balance_carried"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="method",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("CREDIT", "Card"), ("CHECK", "Check")],
                default="CASH",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("PAYMENT", "Payment"),
                    ("REFUND", "Refund"),
                    ("STAYOVER", "Stay-over payment"),
                ],
                default="PAYMENT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("CREDIT", "Credit"), ("CHECK", "Check")],
                max_length=10,
            ),
        ),
    ]
